# Generated by Django 3.2.5 on 2021-07-25 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amostra',
            fields=[
                ('id_amostra', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_amostra', models.CharField(max_length=255)),
                ('metodo_de_coleta', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='exame',
            fields=[
                ('id_exame', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('virus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente_Exame_Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_realizacao', models.DateField()),
                ('data_de_solicitacao', models.DateField()),
                ('id_amostra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.amostra')),
                ('id_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.exame')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('cpf',), name='unique_cpf'),
        ),
        migrations.AddField(
            model_name='exame',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ep3.paciente'),
        ),
        migrations.AddConstraint(
            model_name='amostra',
            constraint=models.UniqueConstraint(fields=('codigo_amostra',), name='unique_codigo_amostra'),
        ),
        migrations.AddConstraint(
            model_name='paciente_exame_amostra',
            constraint=models.UniqueConstraint(fields=('id_paciente', 'id_amostra', 'id_exame', 'data_de_realizacao'), name='unique_id_paciente_amostra_exame'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.UniqueConstraint(fields=('tipo',), name='unique_tipo'),
        ),
        migrations.AddConstraint(
            model_name='exame',
            constraint=models.UniqueConstraint(fields=('virus',), name='unique_virus'),
        ),
    ]
